# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-29 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('processing', models.CharField(max_length=255)),
                ('trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'all_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('user_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AziinDugaar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aziin_dugaar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bagts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numbertype', models.CharField(blank=True, max_length=255, null=True)),
                ('negj', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('honog', models.CharField(blank=True, max_length=255, null=True)),
                ('nuhtsul', models.CharField(blank=True, max_length=255, null=True)),
                ('une', models.IntegerField()),
                ('is_active', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bagts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cashlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(blank=True, max_length=255, null=True)),
                ('orders', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('money_charged', models.IntegerField()),
            ],
            options={
                'db_table': 'cashlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('sku', models.CharField(db_column='SKU', max_length=200)),
                ('is_active', models.IntegerField()),
                ('hyazgaar', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'data_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jwt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('jwt', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jwt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_id', models.IntegerField(blank=True, null=True)),
                ('operation', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('trace_no', models.CharField(blank=True, max_length=6, null=True)),
                ('db_ref_no', models.CharField(blank=True, max_length=16, null=True)),
                ('rrn', models.CharField(blank=True, max_length=12, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=6, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=8, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=15, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=25, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=40, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tc', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'kart_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.TextField(blank=True, null=True)),
                ('billid', models.TextField(blank=True, db_column='billId', null=True)),
                ('date', models.DateTimeField()),
                ('mac_address', models.TextField(blank=True, null=True)),
                ('register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_code', models.TextField(blank=True, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_data', models.TextField(blank=True, null=True)),
                ('lottery', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.CharField(blank=True, max_length=255, null=True)),
                ('vat', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('ttd', models.TextField(blank=True, null=True)),
                ('lottery_warning', models.TextField(blank=True, null=True)),
                ('sales_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lottery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numbertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('types_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'numbertype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_profile_id', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('paid', models.CharField(blank=True, max_length=200, null=True)),
                ('must_pay', models.CharField(blank=True, max_length=200, null=True)),
                ('order_success', models.IntegerField()),
                ('trans_id', models.CharField(blank=True, max_length=200, null=True)),
                ('kiosk_name', models.CharField(blank=True, max_length=200, null=True)),
                ('charge_user_id', models.IntegerField(blank=True, null=True)),
                ('prepaid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prefix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefixab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField()),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prefixab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('type_id', models.CharField(max_length=255)),
                ('bagts_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'price_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('invoice_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qpay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('card_dispenser_comm_open_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'setup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('is_sold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_price', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.CharField(blank=True, max_length=200, null=True)),
                ('is_number_created', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('kiosk_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'sims',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_carddispenser_active', models.IntegerField()),
                ('sim_card_total', models.IntegerField()),
                ('is_casher_active', models.IntegerField()),
                ('cash_total', models.IntegerField()),
                ('printer_counter', models.IntegerField()),
                ('address', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_dispenser_comm_open_code', models.IntegerField(blank=True, null=True)),
                ('sales_id', models.CharField(max_length=255)),
                ('sales_location_id', models.CharField(max_length=255)),
                ('ruim_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type0Fservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'type0fservice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('sku', models.CharField(db_column='SKU', max_length=200)),
                ('is_active', models.IntegerField()),
                ('honog', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'unit_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('pass_status', models.IntegerField(blank=True, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=50, null=True)),
                ('salt', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_id', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
                ('created_user', models.BigIntegerField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('modified_user', models.BigIntegerField(blank=True, null=True)),
                ('access_retry_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kiosk_name', models.CharField(blank=True, max_length=255, null=True)),
                ('register', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_confirmation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('reportid', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=200)),
                ('action_name', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField()),
                ('ip_address', models.CharField(max_length=100)),
                ('receive_content', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('status_reason', models.TextField()),
                ('log_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('register', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('soum', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'us_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('app_name', models.CharField(blank=True, max_length=50, null=True)),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'us_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsGroupPermission',
            fields=[
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='controller.UsGroup')),
            ],
            options={
                'db_table': 'us_group_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsUserGroup',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='controller.User')),
            ],
            options={
                'db_table': 'us_user_group',
                'managed': False,
            },
        ),
    ]
